# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9122c9030e63e150f314a733d5af5706bc812cc7f1caf334e1a8e0d69d5e1b3116de85b0dae1b7f9c2a7e4d3868bac17cb55e596e2a9fe99807e553333a2b282

test:
  secret_key_base: d656c9c83048062cdc1d8c4c8c12feb175bb8b6d36477132b243404404a99233df7c43972c84bffe9aa6e0cfd45c2e7d580ba7d01f17f0d587e4e3f8503da553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
